replaceitem entity @s inventory.0 barrier{CustomModelData:1b,display:{Name:'{"text":"PISTOL","color":"red","italic":"false"}',Lore:['{"color":"yellow","text":"500 Coins","italic":"false"}','{"color":"gray","italic":"false","text":"Close Range Weapon"}','{"color":"gray","italic":"false","text":"Quick Fire Rate, Low Damage"}','{"color":"gray","italic":"false","text":"-------------------"}','{"color":"gray","italic":"false","text":"Range           10 Blocks"}','{"color":"gray","italic":"false","text":"Damage          150 HP"}','{"color":"gray","italic":"false","text":"Rate of Fire    300 RPM"}','{"color":"gray","italic":"false","text":"Reload           1 Second"}','{"color":"gray","italic":"false","text":"Magazine        12 Rounds"}','{"color":"gray","italic":"false","text":"Kick              Minor"}']}}
replaceitem entity @s inventory.1 barrier{CustomModelData:6b,display:{Name:'{"text":"SLUG SHOTGUN","color":"red","italic":"false"}',Lore:['{"color":"yellow","text":"1700 Coins","italic":"false"}','{"color":"gray","italic":"false","text":"Close Range Weapon"}','{"color":"gray","italic":"false","text":"Medium Fire Rate, High Damage"}','{"color":"gray","italic":"false","text":"-------------------"}','{"color":"gray","italic":"false","text":"Range           15 Blocks"}','{"color":"gray","italic":"false","text":"Damage          800 HP"}','{"color":"gray","italic":"false","text":"Rate of Fire    60 RPM"}','{"color":"gray","italic":"false","text":"Reload           3 Second"}','{"color":"gray","italic":"false","text":"Magazine        6 Rounds"}','{"color":"gray","italic":"false","text":"Kick              Major"}']}}
replaceitem entity @s inventory.2 barrier{CustomModelData:3b,display:{Name:'{"text":"SCOUT RIFLE","color":"red","italic":"false"}',Lore:['{"color":"yellow","text":"2500 Coins","italic":"false"}','{"color":"gray","italic":"false","text":"Long Range Weapon"}','{"color":"gray","italic":"false","text":"Medium Fire Rate, Medium Damage"}','{"color":"gray","italic":"false","text":"-------------------"}','{"color":"gray","italic":"false","text":"Range           50 Blocks"}','{"color":"gray","italic":"false","text":"Damage          400 HP"}','{"color":"gray","italic":"false","text":"Rate of Fire    170 RPM"}','{"color":"gray","italic":"false","text":"Reload           1.9 Second"}','{"color":"gray","italic":"false","text":"Magazine        14 Rounds"}','{"color":"gray","italic":"false","text":"Kick              Minor"}']}}
replaceitem entity @s inventory.3 barrier{CustomModelData:5b,display:{Name:'{"text":"ASSAULT RIFLE","color":"red","italic":"false"}',Lore:['{"color":"yellow","text":"3000 Coins","italic":"false"}','{"color":"gray","italic":"false","text":"Medium Range Weapon"}','{"color":"gray","italic":"false","text":"High Fire Rate, Medium Damage"}','{"color":"gray","italic":"false","text":"-------------------"}','{"color":"gray","italic":"false","text":"Range           30 Blocks"}','{"color":"gray","italic":"false","text":"Damage          200 HP"}','{"color":"gray","italic":"false","text":"Rate of Fire    600 RPM"}','{"color":"gray","italic":"false","text":"Reload           2 Second"}','{"color":"gray","italic":"false","text":"Magazine        20 Rounds"}','{"color":"gray","italic":"false","text":"Kick              Minor"}']}}
replaceitem entity @s inventory.4 barrier{CustomModelData:8b,display:{Name:'{"text":"LIGHT SNIPER","color":"red","italic":"false"}',Lore:['{"color":"yellow","text":"4000 Coins","italic":"false"}','{"color":"gray","italic":"false","text":"Long Range Weapon"}','{"color":"gray","italic":"false","text":"Medium Fire Rate, High Damage"}','{"color":"gray","italic":"false","text":"-------------------"}','{"color":"gray","italic":"false","text":"Range           70 Blocks"}','{"color":"gray","italic":"false","text":"Damage          700 HP"}','{"color":"gray","italic":"false","text":"Rate of Fire    80 RPM"}','{"color":"gray","italic":"false","text":"Reload           3 Second"}','{"color":"gray","italic":"false","text":"Magazine        4 Rounds"}','{"color":"gray","italic":"false","text":"Kick              Major"}']}}
replaceitem entity @s inventory.5 barrier{CustomModelData:11b,display:{Name:'{"text":"HEALTH BOOST","color":"red","italic":"false"}',Lore:['{"color":"gray","italic":"false","text":"Immediately heals 500 Health,"}','{"color":"gray","italic":"false","text":"starts Health Regeneration,"}','{"color":"gray","italic":"false","text":"and clears Slow Punch"}']}}
replaceitem entity @s inventory.6 barrier{CustomModelData:10b,display:{Name:'{"text":"DAMAGE MULTIPLYER BONUS","color":"blue","italic":"false"}',Lore:['{"color":"gray","italic":"false","text":"Increases Damage Multiplyer"}','{"color":"gray","italic":"false","text":"by 10%"}','{"color":"gray","italic":"false","text":"(Maximum 10 Upgrades)"}']}}
replaceitem entity @s inventory.7 barrier{CustomModelData:12b,display:{Name:'{"text":"REGENERATION BONUS","color":"green","italic":"false"}',Lore:['{"color":"gray","italic":"false","text":"Increases Base Regeneration"}','{"color":"gray","italic":"false","text":"by 8 health per second"}','{"color":"gray","italic":"false","text":"(Maximum 10 Upgrades)"}']}}
replaceitem entity @s inventory.8 barrier{CustomModelData:13b,display:{Name:'{"text":"HEALTH BONUS","color":"red","italic":"false"}',Lore:['{"color":"gray","italic":"false","text":"Increases Base Health"}','{"color":"gray","italic":"false","text":"by 200"}','{"color":"gray","italic":"false","text":"(Maximum 10 Upgrades)"}']}}
replaceitem entity @s inventory.9 barrier{CustomModelData:2b,display:{Name:'{"text":"REVOLVER","color":"red","italic":"false"}',Lore:['{"color":"yellow","text":"700 Coins","italic":"false"}','{"color":"gray","italic":"false","text":"Medium Range Weapon"}','{"color":"gray","italic":"false","text":"Slow Fire Rate, High Damage"}','{"color":"gray","italic":"false","text":"-------------------"}','{"color":"gray","italic":"false","text":"Range           20 Blocks"}','{"color":"gray","italic":"false","text":"Damage          300 HP"}','{"color":"gray","italic":"false","text":"Rate of Fire    100 RPM"}','{"color":"gray","italic":"false","text":"Reload           2 Seconds"}','{"color":"gray","italic":"false","text":"Magazine        8 Rounds"}','{"color":"gray","italic":"false","text":"Kick              Noticeable"}']}}
replaceitem entity @s inventory.10 barrier{CustomModelData:7b,display:{Name:'{"text":"SPREAD SHOTGUN","color":"red","italic":"false"}',Lore:['{"color":"yellow","text":"1800 Coins","italic":"false"}','{"color":"gray","italic":"false","text":"Close Range Weapon"}','{"color":"gray","italic":"false","text":"Low Fire Rate, High Damage"}','{"color":"gray","italic":"false","text":"-------------------"}','{"color":"gray","italic":"false","text":"Range           10 Blocks"}','{"color":"gray","italic":"false","text":"Damage          1500 HP"}','{"color":"gray","italic":"false","text":"Rate of Fire    60 RPM"}','{"color":"gray","italic":"false","text":"Reload           3 Second"}','{"color":"gray","italic":"false","text":"Magazine        5 Rounds"}','{"color":"gray","italic":"false","text":"Kick              Extreme"}']}}
replaceitem entity @s inventory.11 barrier{CustomModelData:4b,display:{Name:'{"text":"BURST RIFLE","color":"red","italic":"false"}',Lore:['{"color":"yellow","text":"2200 Coins","italic":"false"}','{"color":"gray","italic":"false","text":"Medium Range Weapon"}','{"color":"gray","italic":"false","text":"Medium Fire Rate, High Damage"}','{"color":"gray","italic":"false","text":"-------------------"}','{"color":"gray","italic":"false","text":"Range           40 Blocks"}','{"color":"gray","italic":"false","text":"Damage          750 HP"}','{"color":"gray","italic":"false","text":"Rate of Fire    133 RPM"}','{"color":"gray","italic":"false","text":"Reload           1.9 Second"}','{"color":"gray","italic":"false","text":"Magazine        30 Rounds"}','{"color":"gray","italic":"false","text":"Kick              Minor"}']}}
replaceitem entity @s inventory.12 barrier{CustomModelData:33,display:{Name:'{"text":"SUBMACHINE GUN","color":"red","italic":"false"}',Lore:['{"color":"yellow","text":"1600 Coins","italic":"false"}','{"color":"gray","italic":"false","text":"Close Range Weapon"}','{"color":"gray","italic":"false","text":"High Fire Rate, Low Damage"}','{"color":"gray","italic":"false","text":"-------------------"}','{"color":"gray","italic":"false","text":"Range           15 Blocks"}','{"color":"gray","italic":"false","text":"Damage          200 HP"}','{"color":"gray","italic":"false","text":"Rate of Fire    600 RPM"}','{"color":"gray","italic":"false","text":"Reload           1.3 Second"}','{"color":"gray","italic":"false","text":"Magazine        20 Rounds"}','{"color":"gray","italic":"false","text":"Kick              Noticeable"}']}}
replaceitem entity @s inventory.13 barrier{CustomModelData:9b,display:{Name:'{"text":"HEAVY SNIPER","color":"red","italic":"false"}',Lore:['{"color":"yellow","text":"6000 Coins","italic":"false"}','{"color":"gray","italic":"false","text":"Long Range Weapon"}','{"color":"gray","italic":"false","text":"Slow Fire Rate, High Damage"}','{"color":"gray","italic":"false","text":"-------------------"}','{"color":"gray","italic":"false","text":"Range           200 Blocks"}','{"color":"gray","italic":"false","text":"Damage          2000 HP"}','{"color":"gray","italic":"false","text":"Rate of Fire    30 RPM"}','{"color":"gray","italic":"false","text":"Reload           4 Second"}','{"color":"gray","italic":"false","text":"Magazine        1 Rounds"}','{"color":"gray","italic":"false","text":"Kick              Extreme"}']}}
replaceitem entity @s inventory.14 barrier{CustomModelData:30,display:{Name:'{"text":"BUY 1","color":"gray","italic":"false"}',Lore:['{"color":"yellow","text":"500 Coins","italic":"false"}']}}
replaceitem entity @s inventory.15 barrier{CustomModelData:30,display:{Name:'{"text":"BUY 1","color":"gray","italic":"false"}',Lore:['{"color":"yellow","text":"1000 Coins","italic":"false"}']}}
replaceitem entity @s inventory.16 barrier{CustomModelData:30,display:{Name:'{"text":"BUY 1","color":"gray","italic":"false"}',Lore:['{"color":"yellow","text":"1000 Coins","italic":"false"}']}}
replaceitem entity @s inventory.17 barrier{CustomModelData:30,display:{Name:'{"text":"BUY 1","color":"gray","italic":"false"}',Lore:['{"color":"yellow","text":"1000 Coins","italic":"false"}']}}
replaceitem entity @s inventory.18 barrier{CustomModelData:32,display:{Name:'{"text":"RECYCLE","color":"gray","italic":"false"}',Lore:['{"color":"gray","italic":"false","text":"Recycle a weapon for"}','{"color":"gray","italic":"false","text":"50% its value"}']}}
replaceitem entity @s inventory.19 barrier{CustomModelData:22,display:{Name:'{"text":"KNIFE","color":"red","italic":"false"}',Lore:['{"color":"yellow","text":"FREE","italic":"false"}','{"color":"gray","italic":"false","text":"Melee Weapon"}','{"color":"gray","italic":"false","text":"Average"}','{"color":"gray","italic":"false","text":"-------------------"}','{"color":"gray","italic":"false","text":"Damage          250 HP"}']}}
replaceitem entity @s inventory.20 barrier{CustomModelData:23,display:{Name:'{"text":"SHARP KNIFE","color":"red","italic":"false"}',Lore:['{"color":"yellow","text":"1000 Coins","italic":"false"}','{"color":"gray","italic":"false","text":"Melee Weapon"}','{"color":"gray","italic":"false","text":"Best In Class"}','{"color":"gray","italic":"false","text":"-------------------"}','{"color":"gray","italic":"false","text":"Damage          350 HP"}']}}
replaceitem entity @s inventory.21 barrier{CustomModelData:21,display:{Name:'{"text":"FLASH GRENADE","color":"red","italic":"false"}',Lore:['{"color":"yellow","text":"500 Coins","italic":"false"}','{"color":"gray","italic":"false","text":"Tactical Item"}','{"color":"gray","italic":"false","text":"Stuns Enemy"}','{"color":"gray","italic":"false","text":"-------------------"}','{"color":"gray","italic":"false","text":"Radius           5 Blocks"}','{"color":"gray","italic":"false","text":"Effect           4 Seconds"}']}}
replaceitem entity @s inventory.22 barrier{CustomModelData:20,display:{Name:'{"text":"SMOKE GRENADE","color":"red","italic":"false"}',Lore:['{"color":"yellow","text":"500 Coins","italic":"false"}','{"color":"gray","italic":"false","text":"Tactical Item"}','{"color":"gray","italic":"false","text":"Provides Moderate Cover"}','{"color":"gray","italic":"false","text":"-------------------"}','{"color":"gray","italic":"false","text":"Radius           4 Blocks"}','{"color":"gray","italic":"false","text":"Duration       15 Seconds"}']}}
replaceitem entity @s inventory.23 barrier{CustomModelData:31,display:{Name:'{"text":"BUY 3","color":"gray","italic":"false"}',Lore:['{"color":"yellow","text":"1500 Coins","italic":"false"}']}}
replaceitem entity @s inventory.24 barrier{CustomModelData:31,display:{Name:'{"text":"BUY 3","color":"gray","italic":"false"}',Lore:['{"color":"yellow","text":"3000 Coins","italic":"false"}']}}
replaceitem entity @s inventory.25 barrier{CustomModelData:31,display:{Name:'{"text":"BUY 3","color":"gray","italic":"false"}',Lore:['{"color":"yellow","text":"3000 Coins","italic":"false"}']}}
replaceitem entity @s inventory.26 barrier{CustomModelData:31,display:{Name:'{"text":"BUY 3","color":"gray","italic":"false"}',Lore:['{"color":"yellow","text":"3000 Coins","italic":"false"}']}}


